version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "cargo"
  - package-ecosystem: "cargo"
    directory: "/agent"
    schedule:
      interval: "weekly"
    labels:
      - "agent"
  - package-ecosystem: "cargo"
    directory: "/operator"
    schedule:
      interval: "weekly"
    labels:
      - "operator"
  - package-ecosystem: "cargo"
    directory: "/common"
    schedule:
      interval: "weekly"
    labels:
      - "common"
