---
extends: default
rules:
  document-start:
    present: true
  empty-lines:
    max-end: 1
  indentation:
    spaces: 2
    indent-sequences: false
  line-length: disable
  colons:
    max-spaces-after: -1
