---
depends_on:
- yaml
- rust

steps:
  lint-docker:
    image: hadolint/hadolint:latest-alpine
    commands:
    - hadolint dist/Dockerfile
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.solidite.fr/${CI_REPO}-dist
      registry: git.solidite.fr
      dockerfile: dist/Dockerfile
      username:
        from_secret: repo_user
      password:
        from_secret: repo_password
