---
steps:
  yamllint:
    group: lint
    image: git.solidite.fr/images/ansible:8.2.0
    commands:
    - yamllint -f colored .
  cargo:
    group: lint
    image: docker.io/rust:1.71.0
    commands:
    - export PATH=$PATH:$CARGO_HOME/bin
    - rustup component add clippy
    - cargo clippy -- -Dwarnings -W clippy::semicolon-if-nothing-returned -W clippy::map-unwrap-or -W clippy::similar-names -W clippy::similar-names -W clippy::manual-string-new
  lint-docker-agent:
    group: lint
    image: hadolint/hadolint:latest-alpine
    commands:
    - hadolint agent/Dockerfile
  lint-docker-operator:
    group: lint
    image: hadolint/hadolint:latest-alpine
    commands:
    - hadolint operator/Dockerfile
  lint-docker-dist:
    group: lint
    image: hadolint/hadolint:latest-alpine
    commands:
    - hadolint dist/Dockerfile
  gen-tags:
    image: alpine:latest
    commands:
    - echo "$(awk -v p=1 '$1=="version"&&p==1{gsub("\"","",$3);print $3;p=0}' agent/Cargo.toml)">agent/.tags
    - echo "$(awk -v p=1 '$1=="version"&&p==1{gsub("\"","",$3);print $3;p=0}' dist/Cargo.toml)">dist/.tags
    - echo "$(awk -v p=1 '$1=="version"&&p==1{gsub("\"","",$3);print $3;p=0}' operator/Cargo.toml)">operator/.tags
  build-agent:
    group: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.solidite.fr/${CI_REPO}-agent,${CI_REPO}-agent
      dockerfile: agent/Dockerfile
      tags_file: agent/.tags
      platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
      logins:
      - registry: git.solidite.fr
        username:
          from_secret: repo_user
        password:
          from_secret: repo_password
      - registry: https://index.docker.io/v1/
        username:
          from_secret: docker_user
        password:
          from_secret: docker_password
  build-dist:
    group: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.solidite.fr/${CI_REPO}-dist,${CI_REPO}-dist
      dockerfile: dist/Dockerfile
      tags_file: dist/.tags
      platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
      logins:
      - registry: git.solidite.fr
        username:
          from_secret: repo_user
        password:
          from_secret: repo_password
      - registry: https://index.docker.io/v1/
        username:
          from_secret: docker_user
        password:
          from_secret: docker_password
  build-operator:
    group: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.solidite.fr/${CI_REPO}-operator,${CI_REPO}-operator
      dockerfile: operator/Dockerfile
      tags_file: operator/.tags
      platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
      logins:
      - registry: git.solidite.fr
        username:
          from_secret: repo_user
        password:
          from_secret: repo_password
      - registry: https://index.docker.io/v1/
        username:
          from_secret: docker_user
        password:
          from_secret: docker_password
