[package]
name = "package"
version = "0.1.0"
authors = ["Sébastien Huss <sebastien.huss@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.69"
rhai = { version = "1.12.0", features = ["serde"] }
serde =  { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
log = "0.4.17"
regex = "1.7.3"
openapiv3 = "1.0.2"
indexmap = "1.9.3"
serde_json = "1.0.95"
handlebars = "4.3.6"

[lib]
name = "package"
path = "src/lib.rs"
